#! /bin/sh

DIR=$(dirname $0)/..
cd $DIR
CONFIG=$DIR/scripts/initconfig.json
if [ ! -r $CONFIG ]
then
    echo "Missing configuration file $CONFIG"
    exit 1
fi

if [ "$1" = "confirm" ]
then
    rm db.sqlite3
    ./manage.py migrate
    # superuser.json is a simple json file with username, mail and password properties
    jq -r "\"from django.contrib.auth.models import User; User.objects.create_superuser('\(.username)', '\(.mail)', '\(.password)')\"" $CONFIG | python manage.py shell --plain
    ./scripts/populate
else
    echo "Run with confirm as first parameter"
fi
