#! /bin/bash

# create some news
./manage.py cocoadmin postnews "Launch" "Champagne!" "Launch of the COCo platform. Is there anything more to add?"
./manage.py cocoadmin postnews "Welcome onboard" "Welcome" "Welcome onboard of the COCo platform, enjoy our content"

./manage.py cocoadmin info "Séminaires" ~/www/comin-ocw/contents/lecture/20140707-marcel_lebrun_notes/info.json

for c in 20140825-e2phy1 20140825-e2phy2 20140825-gilles_cohen_tannoudji1 20140825-gilles_cohen_tannoudji2
do
    ./manage.py cocoadmin info "Séminaires" ~/www/comin-ocw/contents/lecture/$c/info.json
done

for c in carto_interactive timeline_interactive  tourner_monter_smartphone
do
    ./manage.py cocoadmin info "Medialab SpeedTraining" ~/www/comin-ocw/contents/medialab/$c/info.json
done

for i in ~/www/comin-ocw/contents/infol1/*/info.json
do
    ./manage.py cocoadmin info "Cours de L1 informatique" "$i"
done

for c in 20131212-gilles_dowek 20140227-denis_bouyssou 20140326-giuseppe_longo 20141002-guy_pujolle
do
    ./manage.py cocoadmin info "Séminaires du LINA" ~/www/comin-ocw/contents/lecture/$c/info.json
done

for i in ~/www/comin-ocw/contents/langagec/l*/info.json;
do
    ./manage.py cocoadmin info "Introduction au langage C" "$i";
done

for i in ~/www/comin-ocw/contents/screencast/*/info.json
do
    ./manage.py cocoadmin info "Projet COCo" "$i"
done

for i in ~/www/comin-ocw/contents/videojournal/open*/info.json
do
    ./manage.py cocoadmin info "Video Journal of Open Education Abstracts Volume 1" "$i"
done
