#! /usr/bin/python

import json
import sys

with open(sys.argv[1], 'r') as f:
    data = json.load(f)
# Build dict for videos / resources
videos = dict( (i['pk'], i)
               for i in data
               if i['model'] == 'coco.video' )
res = dict( (i['pk'], i)
            for i in data
            if i['model'] == 'coco.resource' )

# Add data from coco.resource to matching coco.video
for i in videos.itervalues():
    i['fields'].update(res[i['pk']]['fields'])

# Remove coco.resource elements
data = [ i
         for i in data
         if i['model'] != 'coco.resource' ]

# Save data
with open(sys.argv[2], 'w') as f:
    json.dump(data, f)

